### ISSUE TITLE
Image size issue in list view of listing tab 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#501]
https://secure.helpscout.net/conversation/1485123556/17875?folderId=3817467
<img width="1364" alt="Screenshot 2021-04-16 at 8 11 31 PM" src="https://user-images.githubusercontent.com/24760592/115041270-f170b580-9eef-11eb-90d4-c6dac12c4781.png">

**Comment by 1naveengiri** [comment]
```
.bsui .row.row-cols-md-0 .card .card-img-top {
    max-width: unset !important;
}

```

**Comment by wpdev10** [comment]
![ss](https://user-images.githubusercontent.com/32451578/115230892-8f53c280-a132-11eb-8a46-897b272c8ea0.png)

@1naveengiri We mostly avoid adding custom CSS for bootstrap design layout. We try to use bootstrap classes as much as possible. Looks like it's from AUI. @Stiofan Is there a reason for setting the width to 30%? Because we have to think of GD as well same CSS can be used in GD listing. Should I add 'mw-100' to fix this?
