### ISSUE TITLE
Wrong placeholder for "Confirm password" field on registration form

### ISSUE THREAD

**Issue by amwebch** [AyeCode/userswp#511]
The "Confirm password" field on the registration form displays a wrong placeholder "Password *" instead of "Confirm password *".
This issue has already been reported 10 months ago (see [WP Forum](https://wordpress.org/support/topic/confirm-password-placeholder/)). Currently the label and also the title attribute of the field are correctly populated with "Confirm password *", but unfortunately the placeholder is still not correct.

Given that labels are not displayed in the website (and there is no desire to show them, despite the CSS suggested in the WP ticket the "placeholder only" layout is the one desired by the client), this double "Password" field creates confusion during registration.

**Comment by wpdev10** [comment]
@amwebch 

Can you make sure you are using the latest version of the UsersWP core? It works for me on my test sites. If it doesn't work for you then please create a support ticket on our site http://userswp.io/support or WordPress forum so we can easily assist you further to solve the issue. I am closing this as the issue seems for your site only and we will surely help from our support system.

**Comment by amwebch** [comment]
Done (see [here](https://wordpress.org/support/topic/confirm-password-placeholder-3/)).

NB: I can confirm that I am using the latest version (1.2.2.16) and that the problem still persists.
