### ISSUE TITLE
Cache the results of uwp_get_custom_field_info

### ISSUE THREAD

**Issue by picocodes** [AyeCode/userswp#692]
Checked and this function executes the same db query 196 times in a single page load ( on a page with lots of users ). We can cache the results using a static or global variable to ensure that it only reads the db once.

![Account-–-Noptin](https://user-images.githubusercontent.com/19934448/211497013-159c4a55-4a9e-4fd5-8143-c7e742df4b89.png)

**Comment by sachyya** [comment]
Can you specify the page too where this function is being executed or maybe list out steps to recreate this issue?

**Comment by picocodes** [comment]
Hi @sachyya, install the Query Monitor plugin then open the frontend users page.

A quick fix would be:-

```php
$cache_key = $htmlvar_name . '_' . $form_type;
if ( isset( $GLOBALS['uwp_custom_field_info'][ $cache_key ] ) ) {
	return $GLOBALS['uwp_custom_field_info'][ $cache_key ];
}
```

**Comment by sachyya** [comment]
The multiple calls being made is due to the filter `uwp_get_usermeta` applied in class-meta.php L105 in which `modify_datepicker_value_on_get` is being hooked. That hooked function executes `uwp_get_custom_field_info`. 

In default setting, `modify_datepicker_value_on_get` does nothing to modify to the filter. I suppose it can be omitted. Can you specify the use case of this function? Otherwise, I suppose a simple one would be to omit this filter that in return reduces the function calls.

**Comment by picocodes** [comment]
The function retrieves a field's settings as defined in the UWP form builder. I'm not sure that removing the filter is the correct fix since the function is called in several other places.

**Comment by picocodes** [comment]
Please check how the same issue was fixed in GeoDirectory.

https://github.com/AyeCode/geodirectory/issues/2104
https://github.com/AyeCode/geodirectory/blob/master/includes/custom-fields/functions.php#L364
